- name: NGINX | Install and configure NGINX
  hosts: nginx
  become: true
   
  tasks:
    - name: NGINX | Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL Repo
      yum:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages

    - name: NGINX | Create NGINX config file from template
      template:
        src: ../templates/nginx.conf.j2
        dest: /tmp/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration
